export const USER_ACTIVITIES = {
  LOGIN: 'USER_LOGIN',
  LOGOUT: 'USER_LOGOUT',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  DELETE: 'USER_DELETED',
  PERMANENT_DELETE: 'PERMANENT_DELETE',
  RESTORE: 'USER_RESTORED',
} as const;
